### PR TITLE
Implement srcset for images

### PR DESCRIPTION
**Pull request by lucaslcode**
This only works for selecting from the media library - I couldn't find the dependency to ckeditor5-strapi-upload-plugin, but I did [open a PR](https://github.com/gtomato/ckeditor5-strapi-upload-plugin/pull/6) there too

### CODE REVIEW

**Comment by roslovets** [comment]
Hi, thanks for PR. Could you provide example how it works please?

**Comment by lucaslcode** [comment]
You don't have to do anything - it automatically adds the [`srcset` attribute](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset) to the image tag. 

It can do this because strapi's media library plugin automatically creates different sizes of each image when uploading.

**Comment by roslovets** [comment]
Ok, thanks. Will it works without this PR? https://github.com/gtomato/ckeditor5-strapi-upload-plugin/pull/6

**Comment by roslovets** [comment]
Insert Image button is broken after this change.
image

Apparently because you PR to upload-plugin is not megred yet.

Maybe you can push it providing more information and relibale tests result to @gtomato. It's hard to find time for PR assessment when you need manually test all changes in different scenarios.

**Pull request closed without merging**
